name: 'DisasterConnect'
description: "disaster management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_blue: ^0.8.0
  twilio_flutter: ^0.3.0
  fl_chart: ^0.67.0
  get: ^4.1.4
  protobuf: ^2.1.0
  shake: ^2.2.0 

  cupertino_icons: ^1.0.2
  flutter_config:
  telephony:
  permission_handler:
  google_fonts:
  font_awesome_flutter:
  intl_phone_field:
  url_launcher:
  shared_preferences:
  google_maps_flutter:
  geolocator: 
  custom_sliding_segmented_control:
  material_segmented_control:
  modal_bottom_sheet:
  flutter_svg:
  http:
  flutter_local_notifications:
  timezone:
  dash_chat_2: 
  firebase_core: 
  firebase_auth:
  cloud_firestore:
  firebase_database:
  uuid:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  internet_connection_checker: ^0.0.1


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icon/
    - assets/background/
    - assets/maps/
    - assets/maps/markers/
    - assets/weatherData.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
