// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZZGPASrckhldMeKsR7udFbnEDSxnfZPU',
    appId: '1:319641832184:web:947255ccaf98101564090d',
    messagingSenderId: '319641832184',
    projectId: 'sahayaa-9bc84',
    authDomain: 'sahayaa-9bc84.firebaseapp.com',
    databaseURL: 'https://sahayaa-9bc84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sahayaa-9bc84.appspot.com',
    measurementId: 'G-VB7XS9B4BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhndOn7l1koHhKQl5UWfEBGQxker8J34',
    appId: '1:319641832184:android:63c4cd299fb67c3c64090d',
    messagingSenderId: '319641832184',
    projectId: 'sahayaa-9bc84',
    databaseURL: 'https://sahayaa-9bc84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sahayaa-9bc84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyDNK9E5wNPES0LsQK9Dn9FUsFjG7z5Dg',
    appId: '1:319641832184:ios:a80974d733fe03f064090d',
    messagingSenderId: '319641832184',
    projectId: 'sahayaa-9bc84',
    databaseURL: 'https://sahayaa-9bc84-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sahayaa-9bc84.appspot.com',
    iosBundleId: 'com.example.mobile',
  );
}
